import React from 'react'
import Header from '../components/Header'
import Head from 'next/head'
import Footer from '../components/Footer'
import {useRouter} from 'next/dist/client/router'
import {format} from 'date-fns'
import InfoCard from '../components/InfoCard'
function Search({searchResults}) {
  const router = useRouter()
  const {location,startDate,endDate,noOfGuests} = router.query;

  const formatedStartDate =  format(new Date(startDate),'dd MMMM yy')
  const formatedEndDate =  format(new Date(endDate),'dd MMMM yy')

  const range = `${formatedStartDate} - ${formatedEndDate}`
  return (
    <div>

      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Header placeholder={`${location} | ${range} | ${noOfGuests} guests`}/>
    <div className="max-w-7xl mx-auto px-8 sm:px-16">
      <main className='flex'>
        <section className='flex-grow pt-16 px-6'>
        <p className='text-xs'>300+ stays - {range} - for {noOfGuests} guests</p>
        <h1 className='text-3xl font-semibold mt-2 mb-6'>Stays in {location}</h1>
        <div className='hidden lg:inline-flex space-x-4 mb-5 text-gray-800 whitespace-nowrap'>
          <p className='button'>Cancellation Flexibility</p>
          <p className='button'>Type of Place</p>
          <p className='button'>Price</p>
          <p className='button'>Rooms and Beds</p>
          <p className='button'>More filters</p>
        </div>
        <div className='flex flex-col'>

        {searchResults.map((item,index) => (
          <InfoCard 
          key={index}
          title={item.title}
          img={item.img}
          description={item.description}
          location={item.location}
          price={item.price}
          star={item.star}
          total={item.total} />
          ))}
          </div>
        </section>
      </main>

    </div>
      <Footer/>
    </div>

  )
}

export default Search

export async function getServerSideProps () {
  const searchResults = await fetch('https://www.jsonkeeper.com/b/5NPS')
  .then(res => res.json())

  return {
    props: {
      searchResults
    }
  }
}